# Version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

install:
  - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - set PATH=C:\jruby-9.0.0.0\bin;%PATH%

build_script:
  - ruby -v
  - appveyor AddCompilationMessage "Starting Build"
  - cd C:\projects\logstash
  - rake bootstrap
  - rake test:install-core

branches:
  only:
    - appveyor_test 

test_script:
  - rake test:core
